Feature/custom_dispatchedactionscheduler
Odonno/ReduxSimple pull request #89
Opened 2021-02-15 10:44 UTC by akaegi

2021-02-15 10:45 UTC, akaegi commented
See issue #87

2021-02-16 16:22 UTC, Odonno requested changes

2021-02-16 16:22 UTC, Odonno commented on ReduxSimple.Tests/EffectsActionOrderTest.cs
> +                // TODO: Here it would be nice to pass the store as argument... Then we would not need to reside on a shared variable...
You should be able to do it, now.

2021-02-17 06:45 UTC, akaegi commented on ReduxSimple.Tests/EffectsActionOrderTest.cs
> +                // TODO: Here it would be nice to pass the store as argument... Then we would not need to reside on a shared variable...
Nice 👍 
-> done

2021-02-17 09:49 UTC, merged

2021-04-19 11:36 UTC, akaegi commented
Hi @Odonno When is the next release planned? Because I'm waiting for this feature to be integrated into the nuget package ;-)

2021-04-19 12:10 UTC, Odonno commented
Oh, I thought I did. I will do it now.

2021-04-19 12:37 UTC, Odonno commented
Ok, v3.6.1 will be available soon.

2021-04-19 12:42 UTC, akaegi commented
Thanks a bunch :-)